# https://github.com/openshift/installer/blob/master/docs/dev/libvirt-howto.md
#   1. IP Forwarding is already enabled on Fedora 29 server,
#   2. we run with "--become", so we don't have to Make sure you have permissions for qemu:///system,
# but let's apply the remaining required changes:
- hosts: all
  tasks:
    - name: Configure libvirtd.conf to accept TCP connections
      lineinfile:
        dest: /etc/libvirt/libvirtd.conf
        regexp: "^{{ item.param }}"
        insertafter: "^#?{{ item.param }}"
        line: "{{ item.param }} = {{ item.value }}"
        backup: yes
      with_items:
        - { param: 'listen_tls', value: '0' }
        - { param: 'listen_tcp', value: '1' }
        - { param: 'auth_tcp',   value: '"none"' }
        - { param: 'tcp_port',   value: '"16509"' }
    - name: Configure the service runner to pass --listen to libvirtd
      lineinfile:
        dest: /etc/sysconfig/libvirtd
        regexp: '^#?LIBVIRTD_ARGS="--listen"'
        line: 'LIBVIRTD_ARGS="--listen"'
        backup: yes
      notify: restart libvirtd

    - name: Configure default libvirt Storage Pool
      virt_pool:
        state: present
        name: default
        xml: |
          <pool type='dir'>
            <name>default</name>
            <target>
              <path>/var/lib/libvirt/images</path>
            </target>
          </pool>
    - name: Activate default libvirt Storage Pool
      virt_pool:
        state: active
        name: default
    - name: Set autostart for default libvirt Storage Pool
      virt_pool:
        name: default
        autostart: yes
    - name: Confirm that default libvirt Storage Pool is configured
      virt_pool:
        command: status
        name: "default"

    - name: Set up NetworkManager DNS overlay
      ini_file:
        path: /etc/NetworkManager/NetworkManager.conf
        section: main
        option: dns
        value: dnsmasq
        mode: 0644
        backup: yes
      notify:
        - reload NetworkManager
    - name: Tell dnsmasq to use cluster
      template:
        src: NetworkManager-openshift.conf
        dest: /etc/NetworkManager/dnsmasq.d/openshift.conf
        owner: root
        group: root
        mode: 0644
      notify:
        - reload NetworkManager

    - name: Update firewalld to allow libvirt clients from VMs (port)
      firewalld:
        port: 16509/tcp
        state: enabled
        immediate: yes
        permanent: yes
    - name: Update firewalld to allow libvirt clients from VMs (IPs)
      firewalld:
        source: "192.168.126.0/24"
        state: enabled
        immediate: yes

  handlers:
    - name: restart libvirtd
      service: name=libvirtd state=restarted
    - name: reload NetworkManager
      service: name=NetworkManager state=reloaded

    # TODO Configure default libvirt storage pool
    # TODO Set up NetworkManager DNS overlay
